language: scala
dist: trusty
scala:
      -2.11.8
  
cache:
  directories:
              - $HOME/.sbt
              - $HOME/.ivy2/cache
before_install: cd extension/scalalistener/jupyterspark/
script: sbt package

deploy:
  skip_cleanup: true
  provider: script
  script: echo "Done"
